# Generated by Django 4.2 on 2026-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='access_end_time',
            field=models.TimeField(blank=True, help_text='End time for access (HH:MM format)', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='access_restricted',
            field=models.BooleanField(default=False, help_text='Enable time-based access restrictions for this user'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='access_start_time',
            field=models.TimeField(blank=True, help_text='Start time for access (HH:MM format)', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='allowed_days',
            field=models.CharField(blank=True, default='Mon,Tue,Wed,Thu,Fri', help_text='Comma-separated days (Mon,Tue,Wed,Thu,Fri,Sat,Sun)', max_length=100),
        ),
    ]
