# Generated by Django 4.2 on 2026-08-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilgrim', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='banks.bank')),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pilgrim.pilgrim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('status_updated', 'Status Updated')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_submission_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submission_method', models.CharField(choices=[('manual_form', 'Manual Form'), ('csv_upload', 'CSV Upload'), ('api_webhook', 'API Webhook')], max_length=20)),
                ('sync_timestamp', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_record', to='payment.payment')),
            ],
            options={
                'ordering': ['-sync_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['pilgrim', 'status'], name='payment_pay_pilgrim_04cbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank', 'status'], name='payment_pay_bank_id_be5cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_pay_payment_fe85b9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
    ]
