# Generated by Django 4.2 on 2026-08-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0003_alter_pilgrim_registration_id'),
        ('payment', '0002_payment_payer_contact_payment_payer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pilgrim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pilgrim.pilgrim'),
        ),
    ]
