# Generated by Django 4.2 on 2026-08-31 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings_app', '0004_signatory_remove_signatorysettings_digital_signature_and_more'),
        ('payment', '0003_alter_payment_pilgrim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('pilgrim_first_name', models.CharField(max_length=100)),
                ('pilgrim_last_name', models.CharField(max_length=100)),
                ('pilgrim_email', models.EmailField(blank=True, max_length=254)),
                ('pilgrim_phone', models.CharField(blank=True, max_length=20)),
                ('pilgrim_passport', models.CharField(blank=True, max_length=50)),
                ('pilgrim_dob', models.DateField(blank=True, null=True)),
                ('pilgrim_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_relationship', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payment.payment')),
                ('signatory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.signatory')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment', 'generated_at'], name='payment_rec_payment_310f30_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='payment_rec_receipt_a63c58_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['generated_at'], name='payment_rec_generat_7be7c1_idx'),
        ),
    ]
