# Generated by Django 4.2 on 2026-09-01 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_receipt_receipt_payment_rec_payment_310f30_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payment.payment'),
        ),
    ]
