# Generated by Django 4.2 on 2026-09-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_make_payment_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='payment_rec_payment_310f30_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='payment_rec_generat_7be7c1_idx',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payer_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payer_relationship',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pilgrim_dob',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pilgrim_email',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pilgrim_first_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pilgrim_gender',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pilgrim_last_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pilgrim_passport',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='pilgrim_phone',
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment'], name='payment_rec_payment_47cb25_idx'),
        ),
    ]
