# Generated by Django 4.2 on 2026-09-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_receipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
