# Generated by Django 4.2 on 2026-09-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_receipt_payment_reference'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='receipt',
            name='payment_rec_payment_47cb25_idx',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payment',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_reference',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment_reference'], name='payment_rec_payment_19b235_idx'),
        ),
    ]
