# Generated by Django 4.2 on 2026-09-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_receipt_payment_rec_payment_47cb25_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
