# Generated by Django 4.2 on 2026-08-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('paid', 'Paid'), ('departed', 'Departed'), ('returned', 'Returned')], db_index=True, default='registered', max_length=20)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PilgrimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('id_card', 'ID Card'), ('medical', 'Medical Certificate'), ('insurance', 'Insurance Document'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to='pilgrim_documents/%Y/%m/%d/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pilgrim.pilgrim')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pilgrim',
            index=models.Index(fields=['registration_id'], name='pilgrim_pil_registr_cf4c71_idx'),
        ),
        migrations.AddIndex(
            model_name='pilgrim',
            index=models.Index(fields=['status'], name='pilgrim_pil_status_4138c5_idx'),
        ),
        migrations.AddIndex(
            model_name='pilgrim',
            index=models.Index(fields=['created_at'], name='pilgrim_pil_created_e5c3f6_idx'),
        ),
    ]
