# Generated by Django 4.2 on 2026-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
