# Generated by Django 4.2 on 2026-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0003_alter_pilgrim_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
