# Generated by Django 4.2 on 2026-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0004_alter_pilgrim_address_alter_pilgrim_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
