# Generated by Django 4.2 on 2026-08-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_hajjyear'),
        ('pilgrim', '0005_alter_pilgrim_email_alter_pilgrim_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='hajj_year',
            field=models.ForeignKey(blank=True, help_text='The Hajj year this pilgrim is registered for', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.hajjyear'),
        ),
    ]
