# Generated by Django 4.2 on 2026-08-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0006_pilgrim_hajj_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='region',
            field=models.CharField(blank=True, choices=[('banjul_city', 'Banjul City'), ('kanifing_municipal', 'Kanifing Municipal'), ('brikama_area_council', 'Brikama Area Council'), ('mansakonko_area_council', 'Mansakonko Area Council'), ('kerewan_area_council', 'Kerewan Area Council'), ('kuntaur_area_council', 'Kuntaur Area Council'), ('janjanbureh_area_council', 'Janjanbureh Area Council')], help_text='Gambian region of residence', max_length=50),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='second_contact_name',
            field=models.CharField(blank=True, help_text='Backup contact person name', max_length=100),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='second_contact_phone',
            field=models.CharField(blank=True, help_text='Backup contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='second_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to pilgrim', max_length=50),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='second_contact_whatsapp',
            field=models.CharField(blank=True, help_text='Backup contact WhatsApp number', max_length=20),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp contact number', max_length=20),
        ),
    ]
