# Generated by Django 4.2 on 2026-08-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0007_pilgrim_region_pilgrim_second_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='region',
            field=models.CharField(
                blank=True,
                choices=[
                    ('banjul', 'Banjul (Capital Municipality)'),
                    ('kanifing', 'Kanifing (Municipality)'),
                    ('west_coast', 'West Coast Region'),
                    ('north_bank', 'North Bank Region'),
                    ('lower_river', 'Lower River Region'),
                    ('central_river', 'Central River Region'),
                    ('upper_river', 'Upper River Region'),
                ],
                help_text='Gambian region of residence',
                max_length=50
            ),
        ),
    ]
