# Generated by Django 4.2 on 2026-08-28 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankPaymentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pilgrim_id', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('submission_method', models.CharField(choices=[('manual_form', 'Manual Form'), ('csv_upload', 'CSV Upload'), ('api_webhook', 'API Webhook')], max_length=20)),
                ('payment_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_by_user', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='banks.bank')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_username', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('api_secret', models.CharField(max_length=255)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='banks.bank')),
            ],
            options={
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('manual_form', 'Manual Form Entry'), ('csv_upload', 'CSV Bulk Upload'), ('api_webhook', 'API Webhook Integration')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for the payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='banks.bank')),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
                'unique_together': {('bank', 'method_type')},
            },
        ),
        migrations.AddIndex(
            model_name='bankpaymentsubmission',
            index=models.Index(fields=['bank', 'status'], name='banks_bankp_bank_id_265974_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentsubmission',
            index=models.Index(fields=['pilgrim_id', 'status'], name='banks_bankp_pilgrim_699e90_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentsubmission',
            index=models.Index(fields=['submitted_at'], name='banks_bankp_submitt_e7451d_idx'),
        ),
    ]
