# Generated by Django 4.2 on 2026-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bank_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='created_pilgrim_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='payer_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='payer_relationship',
            field=models.CharField(blank=True, help_text='Relationship to pilgrim: Self, Parent, Spouse, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='pilgrim_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='pilgrim_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='pilgrim_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male (Alagie)'), ('F', 'Female (Aja)')], max_length=1),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='pilgrim_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='pilgrim_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bankpaymentsubmission',
            name='pilgrim_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
