# Generated by Django 4.2 on 2026-08-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0006_pilgrim_hajj_year'),
        ('banks', '0004_bankpaymentsubmission_created_pilgrim_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankpaymentsubmission',
            name='pilgrim_id',
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='pilgrim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_submissions', to='pilgrim.pilgrim'),
        ),
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='pilgrim_registration_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pilgrim registration ID from bank submission', max_length=20),
        ),
    ]
