# Generated by Django 4.2 on 2026-08-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_remove_bankpaymentsubmission_pilgrim_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='payment_view_access',
            field=models.CharField(choices=[('date_restricted', 'Date Filter Only - Admin can only view payments using date filter'), ('unrestricted', 'Unrestricted - Admin can view all payments without date filter')], default='date_restricted', help_text='Controls what payment data bank admins can view', max_length=20),
        ),
    ]
