# Generated by Django 4.2 on 2026-08-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_bank_payment_view_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='location_latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate for access location', null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='location_longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate for access location', null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='location_radius',
            field=models.FloatField(default=1, help_text='Allowed access radius in kilometers'),
        ),
        migrations.AddField(
            model_name='bank',
            name='location_restricted',
            field=models.BooleanField(default=False, help_text='Enable location-based access restrictions for this bank'),
        ),
    ]
