# Generated by Django 4.2 on 2026-09-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_make_payment_nullable'),
        ('banks', '0008_bank_access_end_time_bank_access_restricted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpaymentsubmission',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_submission', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='banks/'),
        ),
    ]
