# Generated by Django 4.2 on 2026-08-29 18:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0005_alter_pilgrim_email_alter_pilgrim_passport_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('aircraft_type', models.CharField(choices=[('B777', 'Boeing 777'), ('B787', 'Boeing 787'), ('A380', 'Airbus A380'), ('A350', 'Airbus A350'), ('A320', 'Airbus A320'), ('B737', 'Boeing 737')], max_length=20)),
                ('total_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('departed', 'Departed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='accommodations.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='accommodations.airport')),
            ],
            options={
                'ordering': ['-departure_date', 'flight_number'],
            },
        ),
        migrations.CreateModel(
            name='FlightBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('people_per_flight', models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_flights', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_pilgrims', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('assignment_priority', models.CharField(choices=[('fifo', 'First In First Out'), ('family', 'Families Together'), ('age', 'Age Priority (Elderly First)')], default='fifo', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_batches', to='accommodations.airport')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_batches', to=settings.AUTH_USER_MODEL)),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_batches', to='accommodations.airport')),
            ],
            options={
                'verbose_name': 'Flight Batch',
                'verbose_name_plural': 'Flight Batches',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('boarding_group', models.CharField(blank=True, max_length=5)),
                ('special_requirements', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('checked_in', 'Checked In'), ('boarded', 'Boarded'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accommodations.flight')),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_assignments', to='pilgrim.pilgrim')),
            ],
            options={
                'ordering': ['flight__departure_date', 'boarding_group', 'seat_number'],
                'unique_together': {('flight', 'pilgrim')},
            },
        ),
    ]
