# Generated by Django 4.2 on 2026-08-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('payment_summary', 'Payment Summary'), ('pilgrim_status', 'Pilgrim Status'), ('bank_performance', 'Bank Performance'), ('daily_activity', 'Daily Activity')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(help_text='Report data in JSON format')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('total_pilgrims', 'Total Pilgrims'), ('total_paid', 'Total Paid'), ('total_pending', 'Total Pending'), ('avg_payment_time', 'Average Payment Time'), ('bank_count', 'Number of Banks'), ('payments_today', 'Payments Today'), ('sync_status', 'Sync Status')], max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='operationalmetric',
            index=models.Index(fields=['metric_type', '-timestamp'], name='dashboard_o_metric__661bc2_idx'),
        ),
    ]
