# Generated by Django 4.2 on 2026-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HajjYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The year of the Hajj (e.g., 2026)', unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'GIA Hajj 2026')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this Hajj year')),
                ('start_date', models.DateField(help_text='Start date of Hajj activities')),
                ('end_date', models.DateField(help_text='End date of Hajj activities')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active Hajj year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hajj Years',
                'ordering': ['-year'],
            },
        ),
    ]
