# Generated by Django 4.2 on 2026-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_hajjyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjyear',
            name='first_deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required first deposit amount for pilgrims', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hajjyear',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this Hajj year'),
        ),
        migrations.AddField(
            model_name='hajjyear',
            name='total_package_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Hajj package fee', max_digits=10, null=True),
        ),
    ]
