# Generated by Django 4.2 on 2026-08-29 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(choices=[('GMD', 'Gambian Dalasi'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='USD', help_text='Default currency for displays', max_length=3)),
                ('base_currency', models.CharField(default='GMD', help_text='Base currency for conversions', max_length=3)),
                ('mode', models.CharField(choices=[('manual', 'Manual - Admin configured rates'), ('realtime', 'Real-Time - API-based rates')], default='manual', help_text='Currency rate mode (manual or realtime)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns these currency settings', on_delete=django.db.models.deletion.CASCADE, related_name='currency_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currency Settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('GMD', 'GMD'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], help_text='ISO 4217 currency code', max_length=3)),
                ('name', models.CharField(help_text='Full currency name', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, £, €)', max_length=5)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate relative to base currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(help_text='Parent currency settings', on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='settings_app.currencysettings')),
            ],
            options={
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['code'],
                'unique_together': {('settings', 'code')},
            },
        ),
    ]
