# Generated by Django 4.2 on 2026-08-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_name', models.CharField(default='GIA Bank Admin', help_text='Name of the authorized signatory', max_length=255)),
                ('signatory_title', models.CharField(default='Bank Administrator', help_text='Title/position of the signatory', max_length=255)),
                ('digital_signature', models.ImageField(blank=True, help_text='Digital signature image (PNG/JPG recommended, transparent background)', null=True, upload_to='receipts/signatures/')),
                ('official_stamp', models.ImageField(blank=True, help_text='Official stamp/seal image (PNG/JPG recommended, transparent background)', null=True, upload_to='receipts/stamps/')),
                ('stamp_color', models.CharField(default='#16a34a', help_text='Color of the stamp (hex format, e.g., #16a34a for green)', max_length=7)),
                ('bank_contact_email', models.EmailField(default='support@giabanking.gm', help_text='Bank contact email for receipt footer', max_length=254)),
                ('bank_contact_phone', models.CharField(default='+220 XXX XXXX', help_text='Bank contact phone for receipt footer', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable use of these signatory settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Signatory Settings',
            },
        ),
        migrations.AlterField(
            model_name='currencysettings',
            name='default_currency',
            field=models.CharField(choices=[('GMD', 'Gambian Dalasi'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='GMD', help_text='Default currency for displays', max_length=3),
        ),
    ]
