# Generated by Django 4.2 on 2026-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_signatorysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_name', models.CharField(help_text='Name of the authorized signatory', max_length=255)),
                ('signatory_title', models.CharField(help_text='Title/position of the signatory', max_length=255)),
                ('digital_signature', models.ImageField(blank=True, help_text='Digital signature image (PNG/JPG recommended, transparent background)', null=True, upload_to='receipts/signatures/')),
                ('official_stamp', models.ImageField(blank=True, help_text='Official stamp/seal image (PNG/JPG recommended, transparent background)', null=True, upload_to='receipts/stamps/')),
                ('stamp_color', models.CharField(default='#16a34a', help_text='Color of the stamp (hex format, e.g., #16a34a for green)', max_length=7)),
                ('email', models.EmailField(blank=True, help_text='Signatory email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Signatory phone number', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Active signatory for receipt generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Signatories',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='signatorysettings',
            name='digital_signature',
        ),
        migrations.RemoveField(
            model_name='signatorysettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='signatorysettings',
            name='official_stamp',
        ),
        migrations.RemoveField(
            model_name='signatorysettings',
            name='signatory_name',
        ),
        migrations.RemoveField(
            model_name='signatorysettings',
            name='signatory_title',
        ),
        migrations.RemoveField(
            model_name='signatorysettings',
            name='stamp_color',
        ),
    ]
