# Generated by Django 4.2 on 2026-09-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_signatory_remove_signatorysettings_digital_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description for this email recipient (e.g., Admin, Finance Team)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email should receive notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable or disable all email notifications')),
                ('notify_on_payment', models.BooleanField(default=True, help_text='Send notification when new payment is created')),
                ('notify_on_receipt', models.BooleanField(default=False, help_text='Send notification when receipt is generated')),
                ('notification_delay', models.IntegerField(default=0, help_text='Delay before sending notification in minutes (0 = immediate)')),
                ('email_from', models.EmailField(default='noreply@giabanking.gm', help_text='Email address to send notifications from', max_length=254)),
                ('email_subject', models.CharField(default='GIA Banking Notification', help_text='Subject line for notification emails', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email Notification Settings',
            },
        ),
    ]
