# Generated by Django 4.2 on 2026-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_emailnotification_emailnotificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencysettings',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual - Admin configured rates')], default='manual', help_text='Currency rate mode', max_length=20),
        ),
    ]
